# Generated by Django 5.0.6 on 2024-06-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutputV1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark_text', models.CharField(max_length=200)),
                ('avg_delta_t', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherV1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_w', models.DateField(max_length=200)),
                ('time_w', models.TimeField(max_length=200)),
                ('temperature', models.IntegerField(max_length=200)),
                ('humidity', models.IntegerField(max_length=200)),
                ('precipitation', models.IntegerField(max_length=200)),
                ('windspeed', models.IntegerField(max_length=200)),
                ('solar_rad', models.IntegerField(max_length=200)),
                ('solar_engy', models.IntegerField(max_length=200)),
                ('delta_t', models.IntegerField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('zipcode', models.IntegerField(max_length=200)),
            ],
        ),
    ]
