# Generated by Django 5.0.6 on 2024-06-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getweather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherv1',
            name='delta_t',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weatherv1',
            name='humidity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weatherv1',
            name='precipitation',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weatherv1',
            name='solar_engy',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weatherv1',
            name='solar_rad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weatherv1',
            name='temperature',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weatherv1',
            name='windspeed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weatherv1',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
