# Generated by Django 5.0.6 on 2024-06-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getweather', '0002_alter_weatherv1_delta_t_alter_weatherv1_humidity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputv1',
            name='avg_delta_t',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherv1',
            name='delta_t',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherv1',
            name='humidity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherv1',
            name='precipitation',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherv1',
            name='solar_engy',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherv1',
            name='solar_rad',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherv1',
            name='temperature',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherv1',
            name='windspeed',
            field=models.FloatField(),
        ),
    ]
