# Generated by Django 5.0.6 on 2024-08-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getweather', '0003_alter_outputv1_avg_delta_t_alter_weatherv1_delta_t_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputv1',
            name='remark_text',
            field=models.CharField(max_length=2000),
        ),
    ]
